# Generated by Django 5.2.3 on 2025-06-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customaccounts',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customaccounts',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customaccounts',
            name='date_joined',
        ),
        migrations.AlterField(
            model_name='brandprofile',
            name='brand_logo',
            field=models.ImageField(default='/media/brand.png', upload_to='brand_logos/'),
        ),
        migrations.AlterField(
            model_name='customaccounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customaccounts',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
