# Generated by Django 5.2.3 on 2025-06-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customaccounts_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccounts',
            name='username',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
