# Generated by Django 5.2.3 on 2025-06-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customaccounts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandprofile',
            name='business_number',
            field=models.CharField(max_length=100),
        ),
    ]
